export { default as Icon } from '@/components/icons/Icon.vue'
export { default as ActivityIcon } from '@/components/icons/iconset/Activity.vue'
export { default as CloseIcon } from '@/components/icons/iconset/Close.vue'
export { default as CommentsIcon } from '@/components/icons/iconset/Comments.vue'
export { default as DownloadPdfIcon } from '@/components/icons/iconset/DownloadPdf.vue'
export { default as EditIcon } from '@/components/icons/iconset/Edit.vue'
export { default as FileClaimsIcon } from '@/components/icons/iconset/FileClaims.vue'
export { default as CloneIcon } from '@/components/icons/iconset/Clone.vue'
